name: Jira Version Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Version Report Script
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_KEY }} # Access the secret here
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
        run: |
          # Install dependencies (if using Node.js, for example)
          npm install

          # Run the script and access the secret through an environment variable
          node script.js
