name: Jira Version Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Version Report Script
        env:
          JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
        run: |
